name: Build GNU Screen RPM on CentOS 7

on:
  workflow_dispatch:

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build screen in CentOS 7 container
        run: |
          docker run --rm -v $PWD:/workspace -w /workspace centos:7 /bin/bash -c '
            # 更换镜像源
            curl -sSL https://linuxmirrors.cn/main.sh -o ./main.sh
            bash ./main.sh
              --source mirrors.aliyun.com \
              --protocol http \
              --use-intranet-source false \
              --install-epel true \
              --backup true \
              --upgrade-software false \
              --clean-cache false \
              --ignore-backup-tips

            # 安装构建依赖
            yum -y update
            yum -y groupinstall "Development Tools"
            yum -y install ncurses-devel wget tar rpm-build pam-devel

            # 下载 screen 源码
            SCREEN_VERSION=5.0.1
            wget https://ftp.gnu.org/gnu/screen/screen-${SCREEN_VERSION}.tar.gz
            tar xzf screen-${SCREEN_VERSION}.tar.gz

            # 准备 rpmbuild 目录结构
            mkdir -p ~/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
            cp screen-5.0.1.tar.gz ~/rpmbuild/SOURCES/

            # 创建 SPEC 文件
            cat > ~/rpmbuild/SPECS/screen.spec <<'EOF'
            Name:           screen
            Version:        5.0.1
            Release:        1%{?dist}
            Summary:        Terminal multiplexer

            License:        GPL
            URL:            https://www.gnu.org/software/screen/
            Source0:        screen-5.0.1.tar.gz

            BuildRequires:  ncurses-devel

            %description
            Screen is a full-screen window manager that multiplexes a physical terminal between several processes.

            %prep
            %setup -q

            %build
            ./configure --prefix=/usr
            make -j\$(nproc) CFLAGS="-std=gnu11"

            %install
            rm -rf %{buildroot}
            make install DESTDIR=%{buildroot}

            %files
            /usr/bin/screen
            /usr/bin/screen-5.0.1
            /usr/share/screen
            /usr/share/man/man1/screen.1.gz

            %changelog
            * Thu Jun 26 2025 GitHub Actions <noreply@github.com> - 5.0.1-1
            - Initial RPM release
            EOF

            # 构建 RPM
            rpmbuild -ba ~/rpmbuild/SPECS/screen.spec

            # 拷贝结果供上传
            cp ~/rpmbuild/RPMS/x86_64/screen-5.0.1-1.el7.x86_64.rpm /workspace/
          '

      - name: Upload RPM as artifact
        uses: actions/upload-artifact@v4
        with:
          name: screen-rpm
          path: screen-5.0.1-1.el7.x86_64.rpm
